Add Patents
hub-usp-inovacao/backend pull request #36
Opened 2021-09-17 20:37 UTC by jooaodanieel

Signed-off-by: João Daniel <jotaf.daniel@gmail.com>

2021-09-19 15:02 UTC, jooaodanieel commented
@T-Guerrero tive uns problemas com o Docker durante a atualização dessa branch depois do #35 ter sido mergeado. Acabei precisando mexer com a `Gemfile.lock` no processo, por isso fiz esse commit -- mas acho que ele merecia ter sido num PR separado

😞  porém 💩 happens

2021-09-20 17:45 UTC, T-Guerrero requested changes

2021-09-20 17:45 UTC, T-Guerrero commented on app/models/patent.rb
> +               classification[:secondary].keys.sort.eql?(%i[cip subarea])
* Área secundária deveria ser opcional, não?
* CIP e Subárea tem um formatinho que da pra validar com regex eu acho

2021-09-20 17:45 UTC, T-Guerrero commented on app/models/patent.rb
> +        ipcs: row[6].split(' | '),
IPC também tem uma regex pra validar

2021-09-20 17:45 UTC, T-Guerrero commented on app/models/patent.rb
> +        photo: row[15]
Na planilha só tem o ID, precisa construir o link se ele existir.

2021-09-20 17:45 UTC, T-Guerrero commented on app/models/patent.rb
> +        url: row[14],
Sem validação de URL

2021-09-20 17:45 UTC, T-Guerrero commented on spec/models/patent_spec.rb
> +  end
No estado atual, só classificação e status precisaria ser testado, né? O resto ta usando validação do próprio rails

2021-09-22 18:58 UTC, T-Guerrero approved these changes

2021-09-22 18:58 UTC, T-Guerrero commented on app/models/patent.rb
> +    clsf.delete(:secondary) if row[2].eql?('N/D')
Para manter a consistência, não seria melhor checar `row[2] == 'N/D' ou row[3] == 'N/D'`?

2021-09-22 18:58 UTC, T-Guerrero commented on spec/models/patent_spec.rb
> +  end
Ainda estou sem entender esses testes, pq estamos testando a própria funcionalidade do rails?

2021-09-23 11:20 UTC, merged