Create multistage building for dev and prod
hub-usp-inovacao/backend pull request #43
Opened 2021-09-26 12:09 UTC by jooaodanieel

2021-09-29 19:00 UTC, T-Guerrero commented
@jooaodanieel to com algumas dúvidas/questionamentos em relação ao Dockerfile:
* Rodar o `entrypoint.sh` sem ter dado bundle install não é um problema? Pois lá dentro rodamos um comando da gema `whenever`.
* Deixar o servidor rodando e só depois dar bundle install não é arriscado?

2021-09-29 19:55 UTC, T-Guerrero requested changes

2021-09-29 19:55 UTC, T-Guerrero commented on config/environments/development.rb
> +  config.hosts << 'www.example.com'
Não entendi essa linha

2021-09-29 19:55 UTC, T-Guerrero commented on dev-compose.yaml
> +    image: hubuspinovacao/backend:${CURR_VERSION:-development}
O que a linha `8` quer dizer?

2021-09-29 19:55 UTC, T-Guerrero commented on Makefile
> +	docker-compose -f prod-compose.yaml run --rm web rake fetch
Não seria melhor rodar `rake fetch:no_reports` ?

2021-09-29 19:56 UTC, T-Guerrero commented
Sugestão: Seria legal fazer um arquivo `README.md` com informações de como rodar o projeto em vez de textos aleatórios.

2021-09-29 20:13 UTC, jooaodanieel commented
Salve, boas dúvidas e preocupações, @T-Guerrero 

> * Rodar o `entrypoint.sh` sem ter dado bundle install não é um problema? Pois lá dentro rodamos um comando da gema `whenever`.

Essa ordem de execução não acontece, porque estamos falando de dois momentos distintos. A ordem dos comandos na `Dockerfile` determinam a sequência em que as camadas _da imagem_ serão criadas. A preocupação/estranhamento com a ordem de execução é pertinente à sequência em que os comandos serão executados _no contêiner_ gerado. Em outras palavras, o comando `ENTRYPOINT` não executa o `entrypoint.sh` durante a criação da imagem, apenas deixa o script registrado para ser rodado logo antes do comando especificado dentro do contêiner -- seja no `CMD`, seja via sobrescrita em algo semelhante a um `docker-compose run web sh`.

> * Deixar o servidor rodando e só depois dar bundle install não é arriscado?

Aqui vale o mesmo comentário: são tempos distintos. O `CMD` é diferente do `RUN` no sentido de que o primeiro não executa nada em tempo de construção da imagem -- semelhante ao `ENTRYPOINT`. O papel do `CMD` é apenas definir o comando padrão de execução _do contêiner_ caso nenhum seja informado -- novamente cito o exemplo do `docker-compose run web sh`, aqui o comando indicado no `CMD` será sobrescrito pelo `sh`.

2021-09-29 20:15 UTC, jooaodanieel commented on config/environments/development.rb
> +  config.hosts << 'www.example.com'
Os testes que o `rspec` roda para requests -- em `specs/requests` -- simulam um cliente acessando externamente a aplicação. O domínio desse cliente é `www.exmaple.com`. Eu adicionei essa configuração para que o Rails evite bloquear, pois isso fazia os testes falharem. Não consegui achar soluções que alterassem o domínio desse cliente fake.

2021-09-29 20:19 UTC, jooaodanieel commented on dev-compose.yaml
> +    image: hubuspinovacao/backend:${CURR_VERSION:-development}
Como temos dois tipos de imagem que serão construídas -- uma de dev e outra de prod --, eu andei tendo problemas para testar na minha máquina o funcionamento do multistage. Ele quebrava basicamente porque não entendia que eram imagens distintas e sobrescrevia a de dev com a de prod (ou vice e versa, dependendo da ordem em que eu testava os builds). Esse não é um problema que aconteceria na prática, porque em teoria nas nossas máquinas só precisamos da imagem de dev e no IF só precisamos da de prod. Porém para evitar dor de cabeça, resolvi nomear as imagens geradas usando essa interpolação de variáveis. Na prática, o docker-compose aceita uma variável `CURR_VERSION` para o build e, caso nenhuma seja informada, ele preenche com o padrão `development` (análogo para a de prod). Isso inclusive nos dá um pouco mais de versatilidade num futuro se quisermos nomear as imagens de desenvolvimento com relação à funcionalidade sendo desenvolvida e evitar conflitos desse tipo que eu tive, porém com versões de dev.

2021-10-01 23:37 UTC, T-Guerrero approved these changes

2021-10-01 23:37 UTC, T-Guerrero commented on README.md
> +The target are as follows, being necessary to run `make <target>`:
linha `11`: Seria `targets`, não?

2021-10-01 23:37 UTC, T-Guerrero commented on README.md
>  [![Maintainability](https://api.codeclimate.com/v1/badges/8b317823f31c83a4bb3b/maintainability)](https://codeclimate.com/github/portal-solus/backend/maintainability)
Não é foco desse PR, mas mudamos o nome da org para `hub-usp-inovacao`, não seria bom mudar o codeClimate? (não sei como funciona)

2021-10-05 13:41 UTC, merged