Add output to csv
hub-usp-inovacao/backend pull request #54
Opened 2021-11-03 17:48 UTC by T-Guerrero

2021-11-03 18:17 UTC, jooaodanieel requested changes
No mais, não entendi onde que de fato ficou melhor a abordagem usando um `Hash` ao invés de `Array` -- mas talvez esse seja um ponto positivo.

2021-11-03 18:17 UTC, jooaodanieel commented on app/models/company_update.rb
> -  field :delivered, type: Boolean, default: false
Essa linha do `delivered` foi removida intencionalmente?

2021-11-03 18:17 UTC, jooaodanieel commented on lib/tasks/mailer.rake
> -  end
Remover isso não volta a mandar um email vazio?

2021-11-03 18:17 UTC, jooaodanieel commented on app/models/company_update.rb
> +    max_partners = 5
Esse tipo de valor é uma configuração, faz sentido então jogá-lo para uma variável de ambiente ao invés de deixar hardcoded aqui.

2021-11-03 18:17 UTC, jooaodanieel commented on app/models/company_update.rb
> +      end
Esse bloco tá bem pesado de entender o funcionamento, vale a pena quebrar em algumas funções auxiliares.

2021-11-03 18:27 UTC, T-Guerrero commented on app/models/company_update.rb
> -  field :delivered, type: Boolean, default: false
Sim. Pelo o que eu entendi, vamos armazenar todo o histórico de atualização no csv, não é? Ai acho que não faz sentido a existência dessa variável mais

2021-11-03 18:27 UTC, T-Guerrero commented on lib/tasks/mailer.rake
> -  end
boa

2021-11-04 12:27 UTC, jooaodanieel requested changes
Senti falta de testes na geração dos CSVs

2021-11-04 12:27 UTC, jooaodanieel commented on app/models/company_update.rb
> +    (0..max_partners - 1).each do |i|
O `Range` pode ser inclusivo ou exclusivo. Nesse caso, cê pode usar o exclusivo com três pontos: `0...max_partnerts` (ao invés de `0..max_partners - 1`), ele vai fazer exatamente o que você quer

2021-11-04 12:27 UTC, jooaodanieel commented on app/models/company_update.rb
> +        row.concat(fetch_partners_data_from(max_partners, %w[name email bond unity nusp],
Confesso que não to gostando muito do uso do `fetch` aqui. Você não tá buscando de outro lugar, você tá transformando dados que você já tem, certo?
Além disso, `attributes_data` parece redundante.
O que as funções estão fazendo, em um nível de abstração mais alto? Isso vai ajudar a nomeá-las melhor.

2021-11-04 12:27 UTC, jooaodanieel commented on app/models/company_update.rb
> +  end
Essa função poderia chamar `sanitiize_value` ou `treat_nil`.

2021-11-05 18:46 UTC, jooaodanieel approved these changes

2021-11-05 18:47 UTC, merged