add skill with terminal attributes
hub-usp-inovacao/backend pull request #64
Opened 2021-11-19 20:51 UTC by jooaodanieel

TODO: criar os outros atributos como modelos nested, para facilitar a manutenção

Signed-off-by: João Daniel <jotaf.daniel@gmail.com>

2021-11-22 18:33 UTC, T-Guerrero requested changes

2021-11-22 18:33 UTC, T-Guerrero commented on app/models/skill.rb
> +  embeds_many :research_groups
Estão faltando (com base no front):
* Vínculo com a USP (ta em vermelho na planilha mas a gente usa no Hub)
* Campus*
* Área
  * Major
  * Minor
* Telefone Institucional
* Data limite do vinculo com a USP

\* Tem que conversar com eles pq não ta fazendo muito sentido isso. As unidades podem vir separadas por ';' porém aparentemente só tem um campus definido na planilha. Outra parada é que tem duas colunas adicionais que, tecnicamente, seria para especificar uma segunda unidade e o vínculo com ela, mas não faz sentido usar isso se eles tão separando por ';'

2021-11-22 18:33 UTC, T-Guerrero commented on app/models/skill.rb
> +  embeds_many :research_groups
No front tem um código adicional para o Campus que o André pediu pra gente faz um tempo. Se o campus não existir na planilha, ele pediu para inferir através da unidade.

2021-11-22 18:33 UTC, T-Guerrero commented on app/models/skill.rb
> +  embeds_many :research_groups
Idem para a área major ser inferida através da área minor

2021-11-22 18:33 UTC, T-Guerrero commented on app/models/skill.rb
> +  end
Da pra generalizar pra um método só esses três métodos

2021-11-22 18:33 UTC, T-Guerrero commented on app/models/research_group.rb
> +  end
Terminei de dar o review e acho que entendi por que você não ta salvando aqui -- ele da erro porque não ta vinculado com o objeto pai, certo? Se for isso, acho que seria legal ou renomear o método pra "new_from" ou usar `has_many e belongs to` no lugar do `embeed`.

2021-11-22 18:33 UTC, T-Guerrero commented on spec/requests/skill_spec.rb
> +    ]
Acho que seria legal fazer igual os outros testes de request e usar o `create` em vez do `create_from`, pq ai não precisa definir valores vazios e tbm fica em formato de um objeto bonitinho

2021-11-22 18:38 UTC, T-Guerrero requested changes

2021-11-22 18:38 UTC, T-Guerrero commented on app/models/skill.rb
> +  validates :name, :email, :lattes, presence: true
Nome tem que ser único

2021-11-22 18:59 UTC, jooaodanieel commented on app/models/research_group.rb
> +  end
Acho que a ideia de mudar o nome para `new_from` é melhor. Não acho que seja o caso de modelar usando `has_many`/`belongs_to`, porque isso é o esquema de chave-estrangeira e referência que a modelagem relacional adota, e aqui a adoção do mongo fica melhor com modelagem do `embed` mesmo.

2021-11-22 19:05 UTC, jooaodanieel commented on spec/requests/skill_spec.rb
> +    ]
É que aqui eu quis fazer o fluxo como se os dados estivessem vindo das planilhas, manja? Aí com array simula isso, no maior espírito "já que é pra fazer teste de integração..."
Mas confesso que não terminei de "processar" essa abordagem ainda pra saber se eu gosto ou não.
Vou deixar assim maturando um pouco, enquanto eu trabalho no resto das coisas.

2021-11-29 14:09 UTC, T-Guerrero commented on app/models/skill.rb
> +      infer_campus(unis[0])
Ainda to meio incomodado com essa inconsistência dos dados na planilha, queria conversar disso com o André

2021-11-29 14:09 UTC, T-Guerrero commented on app/models/skill.rb
> +  embeds_many :research_groups
Deixo algumas validações como sugestão pra você ver se fazem sentido:
* `limit_date`: Checar se não é uma data no passado; acredito que essa validação ajude a identificar pessoas que não deveriam estar mais na planilha.
* fazer validação do `campus` e `area`

2021-11-29 14:09 UTC, T-Guerrero commented on spec/models/skill_spec.rb
> +  it 'is valid with empty array' do
acho que `empty phones array` é mais específico

2021-12-01 14:04 UTC, jooaodanieel commented on app/models/skill.rb
> +  embeds_many :research_groups
Pelo que me lembro, o comportamento sobre o `limit_date` era de só exibir no front se a data fosse no futuro; quando ela deixasse de ser no futuro, o front deixaria de exibir -- mas não vai ser removido da planilha.

Sobre essa validação, prefiro esperar falarmos com o André -- puxei no Telegram sobre isso

2021-12-01 14:19 UTC, T-Guerrero approved these changes

2021-12-01 18:06 UTC, merged